version: "3.9"

services:
  cron:
    image: ${NAME}:${VERSION}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        VERSION: ${VERSION}
        NAME: ${NAME}
    command: /app/project_template
    environment:
      TZ: 'Asia/Tashkent'
      DEBUG: 'true'
      VERSION: ${VERSION}
    volumes:
      - ./volumes/log:/app/log
      - ../src/config/conf.yaml:/app/conf.yaml
    stop_grace_period: 2s
